### ISSUE TITLE
Null value when posted in .NET Core

### ISSUE THREAD

**Issue by MenyBottles** [therealparmesh/object-to-formdata#107]
Just to mention in case someone runs into this.

When posting a file in a nested object to a controller, it is always null, it just happens with types of IFormFile, seems like the issue is the key in the formdata.

Instead of setting the key to `obj[nested]` it should go like `obj.nested`. I changed the key const to `const key = pre ? pre + "." + prop : prop;` and it worked fine. Like I said, all the other props worked fine, just the files are the one who always post null.

**Comment by felaray** [comment]
same issue.

**Comment by therealparmesh** [comment]
I'm thinking about adding a configuration option to allow for choosing between `.` and `[]` delimiters.

**Comment by electrocnic** [comment]
> I'm thinking about adding a configuration option to allow for choosing between `.` and `[]` delimiters.

I just ran into this issue as well and was looking for exactly this configuration option. How fast could you add it? I have to use your code as a modified copy inside my project in the meanwhile (instead of a node_module).

However thanks for the great work, it is indeed a nice util!

**Comment by therealparmesh** [comment]
@electrocnic It looks like a custom formatter function (that provides the consumer with information like `isObject` or `isArray`) may be a better option. I'll look into this soon.

**Comment by therealparmesh** [comment]
I've added a new configuration option called `dotsForObjectNotation` in v4.3.0 that should help solve most of the cases brought up here. I think we should create new issues for new cases.
