### ISSUE TITLE
BUG - Module Not Found via Webpack

### ISSUE THREAD

**Issue by noonii** [therealparmesh/object-to-formdata#110]
```
Uncaught ReferenceError: module is not defined
    at Module../node_modules/object-to-formdata/dist/index.mjs (VM406 main.video-service.js:112066)
    at __webpack_require__ (VM406 main.video-service.js:726)
```

To solve this issue, put your `src/index.js` at the root dir (i.e. outside of `/src`)

When bundled via webpack and probably gulp too these errors occur.

**Comment by noonii** [comment]
@therealparmesh

**Comment by therealparmesh** [comment]
I use `microbundle` to handle all build logic, so I don’t think there’s an issue there.

This looks like a potential issue with your build configuration. Can you post it here?

**Comment by noonii** [comment]
@therealparmesh You're right, my webpack extensions did not include `.mjs`.

I'll have to see if it's feasible to include it because loads of other projects at this company are using a private internal webpack config. 

On another note, is there a reason you chose `.mjs` specifically?

**Comment by therealparmesh** [comment]
https://github.com/developit/microbundle/commit/8cc0d7b3374c5dcaa745ea37b21b5ee7f975c882

**Comment by noonii** [comment]
@therealparmesh Looks like [microbundle docs](https://github.com/developit/microbundle/blob/master/README.md#new-modern-js) removed `.mjs` from `module`

`"module": "dist/index.module.js",  // modern ES2017 bundle`


To have webpack users benefit from this lib, can you update the 

https://github.com/therealparmesh/object-to-formdata/blob/7a2d4c66ce3bb58e46ab58854ef33f78b7156642/package.json#L17

**Comment by therealparmesh** [comment]
Correct - though since I implemented it when the old README was around, I just followed the patterns there.

I think this works for most people because of [Webpack configuration defaults](https://webpack.js.org/configuration/resolve/#resolveextensions).

**Comment by therealparmesh** [comment]
Can you try 3.0.8?

**Comment by noonii** [comment]
Nice, it's working like a charm.

Thank you for the update!
