### ISSUE TITLE
Bad formatting 

### ISSUE THREAD

**Issue by stateradev1** [therealparmesh/object-to-formdata#122]
I'm having issues about formating...
I'm formatting and sending to the server this
```
someOtherProperties...
hasDays: [
  someOthersProperties
  routine_day: [
    image: File
    routine_day_exercises: []
    status: 1
    title: string
  ]
]
```
But if i log on the server i'm getting
```
someOtherProperties...
hasDays: [
  someOthersProperties
  routine_day: [
    image: File
    ],
  routine_day: [
      status: 1
    ],
  routine_day: [
      title: string
    ],
  ]
]
```
I guess it has something to do with recursivity...

**Comment by Woloja** [comment]
> I'm having issues about formating...
> I'm formatting and sending to the server this
> 
> ```
> hasDays: [
>   routine_day: [
>     image: File
>     routine_day_exercises: []
>     status: 1
>     title: string
>   ]
> ]
> ```
> I guess it has something to do with recursivity...

Hi, you have very strange json format, maybe its incorrect?

try this structure/
 ```
 hasDays: [{
                routine_day: [
                    {
                        image: (binary),
                        routine_day_exercises: [...array],
                        status: 1,
                        title: "some str 1"
                    },
                    {
                        image: (binary),
                        routine_day_exercises: [...array],
                        status: 0,
                        title: "some str 2"
                    }
                ]
            }];
```

**Comment by ioev** [comment]
I'm having a similar(ish) problem, trying to serialize an object for Ruby on Rails.  I have an object that looks like:
```
{
  reasons: [1, 2, 3],
  people: [{
    name: "John"
  }, {
    name: "Joe"
  }]
}
```

Which generates (using indices: true):
```
reasons[0]: 1
reasons[1]: 2
reasons[2]: 3
people[0][name]: John
people[1][name]: Joe
```

But I want it to look like:
```
reasons[]: 1
reasons[]: 2
reasons[]: 3
people[0][name]: John
people[1][name]: Joe
```

Maybe the Array code could check if the nested value is an object, and if not, don't render the index value?

**Comment by therealparmesh** [comment]
> Maybe the Array code could check if the nested value is an object, and if not, don't render the index value? TBH, I feel like index should always be present if the value is an object, and it should be omitted if it's any primitive type.

This would be a breaking change for existing consumers. I think the only solution is to add more flags unfortunately.
