### ISSUE TITLE
Releases tag

### ISSUE THREAD

**Issue by dsrini-open** [therealparmesh/object-to-formdata#126]
Hi,

Thanks for your help on a good project!

Before releasing, could the releases be tagged so we have a way to go backward and fetch/see the old code base?

It also helps if one can add info with release notes.

**Comment by therealparmesh** [comment]
I'll look into this soon. I do this with all my other little projects, but since this one is so old, I didn't start doing it here.

**Comment by therealparmesh** [comment]
I pushed as many tags as possible. Hopefully this helps!
