### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by yohney** [therealparmesh/object-to-formdata#14]
Not cool.. Previous version had second parameter "postData", and now it is config.. Luckily, found it, but broke my code in production since CI pulled later version which was actually incompatible. You should've added version 2 to indicate breaking changes..

**Comment by therealparmesh** [comment]
Sorry to hear that. I did not expose that in the README, but I can see that others may dig into source and use that capability. I'll figure something out. Thank you!

**Comment by therealparmesh** [comment]
Fixed.
