### ISSUE TITLE
Can you add option to don't add null, undefined, empty to formdata ?

### ISSUE THREAD

**Issue by npdung** [therealparmesh/object-to-formdata#18]
Can you add option to don't add null, undefined, empty to formdata ?

**Comment by therealparmesh** [comment]
Do you mind looking over the tests and pointing out ones you’d like to see configurable?

**Comment by npdung** [comment]
In my case, i have a edit user information form ( name, password, .... ). When i submit form, if form haven't password field then update information with out change password and vice versa. 

`let form = { 
   name: 'username', password: null
}
`

So i want an option 
`const options = {
    removeEmpty: true
}`
to don't add field empty to form data.

Input 1: 
```
const formData = objectToFormData({
  name: 'username',
  password: null
})
```
Expected:
```
expect(formData.get('name')).toBe('username')
expect(formData.get('password')).toBe(null)
```

Input 2: 
```
const formData = objectToFormData({
  name: 'username',
  password: undefined
})
```
Expected:
```
expect(formData.get('name')).toBe('username')
expect(formData.get('password')).toBe(null)
```

Input 3: 
```
const formData = objectToFormData({
  name: 'username',
  password: ''
})
```
Expected:
```
expect(formData.get('name')).toBe('username')
expect(formData.get('password')).toBe(null)
```

**Comment by therealparmesh** [comment]
Please check out version 1.6.1! It should solve this for `null` values by way of configuration. Thank you.
