### ISSUE TITLE
boolean fields are getting converted to strings

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [therealparmesh/object-to-formdata#187]
Hi,

is there any reason why boolean values get converted to strings?
Imho this should not happen?

**Comment by iyatx** [comment]
boolean values: false => 0 and true => 1

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah sure, but why as strings "0" and "1", not as numbers 0 and 1?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you for the explanation :) /s

**Comment by joemaffei** [comment]
> Yeah sure, but why as strings "0" and "1", not as numbers 0 and 1?

Because FormData values are either strings or Blobs.
https://developer.mozilla.org/en-US/docs/Web/API/FormData/append
