### ISSUE TITLE
Duplicate array suffix

### ISSUE THREAD

**Issue by joepie91** [therealparmesh/object-to-formdata#2]
When feeding in data where the array fields *already* have an array suffix (`[]`), like so:

```js
let formData = objectToFormData({
	'foo[]': ["bar", "baz"]
});

console.log(JSON.stringify(Array.from(formData.entries())))
```

... this module produces the following (JSON-stringified) entries:

```json
[
	["foo[][]", "bar"],
	["foo[][]", "baz"]
]
```

... whereas the output *should* be as follows:

```json
[
	["foo[]", "bar"],
	["foo[]", "baz"]
]
```

The cause of this is [line 25](https://github.com/therealparmesh/object-to-formdata/blob/2d1a977525da813e2b8a5bd390219ff236f5e111/index.js#L25), which blindly adds a `[]` suffix without checking whether one already exists. The fix would be to first check whether the field name already ends with `[]`.

EDIT: Fixed expected output.

**Comment by therealparmesh** [comment]
Closing this issue after reviewing and approving the fix.
