### ISSUE TITLE
Another way of specifying the key of an object from an array

### ISSUE THREAD

**Issue by kryvorotenko** [therealparmesh/object-to-formdata#200]
Hey!

Your solution is quite universal, but in my situation it does not work completely.
I am using Spring Boot on the server side and it expects the keys be like `key[0].key`
But unfortunately, this library parses json as `key[0][key]` and therefore the server cannot recognize data

Is it possible to introduce such an option?

My test case:
![image](https://user-images.githubusercontent.com/55698663/145683310-b5dbf413-b107-41a1-be5c-4827e2944ae2.png)
It must be like:
`followedNiches[0].id: 2`
`followedNiches[1].id: 4`
`followedNiches[2].id: 5`

And this is log of my server:
![image](https://user-images.githubusercontent.com/55698663/145683358-776e9d41-5f92-49c8-9556-880d37d4b143.png)

Or am I missing something?

**Comment by therealparmesh** [comment]
That's a great question. I've received multiple requests for dot notation for object paths. I'll look into it soon. Thanks!

**Comment by therealparmesh** [comment]
What should plain objects look like in your situation?

**Comment by kryvorotenko** [comment]
Any like this:
‘object.field[0].field’
‘field[0].field’

**Comment by therealparmesh** [comment]
Please check out v4.3.0!
