### ISSUE TITLE
Nested nested objects are being pushed up a level

### ISSUE THREAD

**Issue by Nikola-Milovic** [therealparmesh/object-to-formdata#211]
Maybe I am doing something incorrectly but having an object like

```
obj = {
  prop1 : {
     prop2 : {
        prop3: value,
        prop4: value,
     }
  }
}
```

Will push the `props2` up a level, it doesn't nest deeper than 1 level. It will become

```
obj = {
  prop1 : {
  },
  prop2 : {
     prop3: value,
     prop4: value,
  }
}
```

Any way around this behavior?

**Comment by therealparmesh** [comment]
I'm not able to reproduce this behavior on the latest version.
