### ISSUE TITLE
Make this work with React Native without defining global polyfill

### ISSUE THREAD

**Issue by cseelus** [therealparmesh/object-to-formdata#27]
Would that be possible?

**Comment by therealparmesh** [comment]
We could allow you to pass in a `FormData` interface as an option. Would that work?

**Comment by cseelus** [comment]
Yes, sounds like a plan ;-)

**Comment by therealparmesh** [comment]
Also - the third parameter allows you to pass in your own FormData instance to start with. If you do this you shouldn’t need to polyfill globally.

**Comment by therealparmesh** [comment]
Closing as you can pass a form data instance in yourself.
