### ISSUE TITLE
Feature request: Boolean value handling

### ISSUE THREAD

**Issue by juhasev** [therealparmesh/object-to-formdata#30]
New option would be nice that lets you specify to convert boolean values to 0 and 1 respectively as opposed to string values "true" and "false". Right now the automatic conversion to string values is not compatible with Laravel's built in validation system which accepts string "0" and "1" / 0 or 1 or boolean true / false. You do want to maintain strict type checking in JS code so using 0 and 1 is not a good idea. The best option at the moment is to just convert the boolean values before running the final object thru this script.

**Comment by therealparmesh** [comment]
I'll take a closer look at this soon. Thank you!

**Comment by vgsystems** [comment]
It's a must for Laravel, completely agree with @juhasev 

Thanks @therealparmesh !

**Comment by asingh04** [comment]
Hi
Can i pick this is up as a starter?

**Comment by therealparmesh** [comment]
Apologies for the delay. I went ahead and pushed out a new version to address this. Check out v2.3.0.
