### ISSUE TITLE
es6 syntax in dist folder (e.g. arrow functions)

### ISSUE THREAD

**Issue by doits** [therealparmesh/object-to-formdata#44]
I'm using this in a [vue-cli](https://github.com/vuejs/vue-cli) project and I noticed that I have es6 code in my transpiled output which looks like this:

**const r=t=>** void 0===t,i= **t=>** Array.isArray(t),o=t=>t&&"number"==typeof t.size&&"string"==typeof t.type&&"function"==typeof t.slice,a=(t,e,n,s)=>{if((e=e||{}).indices=!r(e.indices)&&e.indices,e.nullsAsUndefined=!r(e.nullsAsUndefined)&&e.nullsAsUndefined,n=n||new FormData,r(t))return n;if((t=>null===t)(t)) [...]

Because of the `nullsAsUndefined` I traced it back to this module.

Other dependencies get transpiled afaik or at least do not have es6 could in the compiled output. I don't know if this has something to do with how `object-to-formdata` is set up or how other projects do it, but somehow it should not output es6 code when using babel to polyfill/transpile things.

Is there something we can do to avoid this?

**Comment by doits** [comment]
Hmm I found out that it looks like I have to use [transpiledDependencies](https://cli.vuejs.org/config/#transpiledependencies) in my vue-cli project to explicitly enable transpiling of `object-to-formdata` module, because by default `node_modules` are not transpiled automatically (which I thought they are).

Then I can only assume that other modules are simply transpiled with more browser support than `object-to-formdata` by default. If this is true maybe you should transpile and publish the `dist` version of `object-to-formdata` with more browser support, too (e.g. no es6 syntax).

**Comment by therealparmesh** [comment]
Thank you for catching this! I fixed this issue in 2.1.1.
