### ISSUE TITLE
not working with angular8..please assist

### ISSUE THREAD

**Issue by SalkiDixit** [therealparmesh/object-to-formdata#51]

**Comment by SalkiDixit** [comment]
@therealparmesh I updated my angular version from 7 to 8...it seems that is not working with ng8, kindly assist

**Comment by therealparmesh** [comment]
Do you have any more details?

**Comment by joelmuskwe** [comment]
**Same here**
using the following import statement:
import objectToFormData from 'object-to-formdata';


**_Error Message:_**
import objectToFormData
Module '"*/node_modules/object-to-formdata/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flagts(1259)
index.d.ts(1, 1): This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

**Comment by therealparmesh** [comment]
Try importing from `object-to-formdata/umd`

**Comment by joelmuskwe** [comment]
still not working please see attached:
<img width="701" alt="Screenshot 2019-10-17 at 08 14 16" src="https://user-images.githubusercontent.com/5989937/66982502-8bb32b80-f0b6-11e9-962b-d33f492be729.png">

**Comment by fdev** [comment]
This workaround worked for me:

```js
import objectToFormData from 'object-to-formdata/dist/umd'
```

**Comment by therealparmesh** [comment]
`import * as objectToFormData from 'object-to-formdata'`?

If not that, I would try to adjust your `tsconfig.json` to `allowSyntheticDefaultImports: true`.

**Comment by joelmuskwe** [comment]
Hi i noticed i was still facing some issues after doing the: **Refactoring types to allow import in TypeScript projects without allowSyntheticDefaultImports** pull request.

So what i ended up doing was a rewrite using typescript first.

If you can review this: [Typescript Version V2](https://github.com/joelmuskwe/object-to-form-data-v2) before i make changes to my fork and put in a pull request.

i also just published a demo package to test before i delete it: **npm i object-to-formdata-v2**

**Comment by therealparmesh** [comment]
I moved the package away from a default export in version 3.0.0.
