### ISSUE TITLE
Wrong formatting in arrays, fix.

### ISSUE THREAD

**Issue by jmoguelruiz** [therealparmesh/object-to-formdata#6]
Hi, @therealparmesh I'm using **object-to-formdata** is very usefully.

Well I have the following example data to convert:
```json
{
  "phones": [
   {
      "number": 9999999,
      "code": 52,
      "contact": "Maria"
   }
 ]
};
```

I convert the information and process it into php and the result of array is the follow:
```php
[
    'phones' => [
        [
            'number' => '9991944318',
        ],
        [
            'code' => '52',
        ],
        [
            'contact' => 'Maria',
        ],
    ],
]
```

as you can see each item is within an array.

I solved this problem as follows:
```javascript
function objectToFormData (obj, fd, pre) {
  fd = fd || new FormData()

  Object.keys(obj).forEach(function (prop) {
    var key = pre ? (pre + '[' + prop + ']') : prop

    if (isObject(obj[prop]) && !isArray(obj[prop]) && !isFile(obj[prop])) {
      objectToFormData(obj[prop], fd, key)
    } else if (isArray(obj[prop])) {

       // HERE.
       // I get the index from the array
      obj[prop].forEach(function (value, index) {

       // HERE.
       // I pass the index to makeArrayKey.
        var arrayKey = makeArrayKey(key, index)
        if (isObject(value) && !isFile(value)) {
          objectToFormData(value, fd, arrayKey)
        } else {
          fd.append(arrayKey, value)
        }
      })
    } else {
      fd.append(key, obj[prop])
    }
  })

// HERE.
// I receive the index as default "null".
function makeArrayKey (key, index = null) {
  if (key.length > 2 && key.lastIndexOf('[]') === key.length - 2) {
    console.log('aqui en solo key');
    return key
  } else {
    // HERE.
    // I valid the existence of the index to indicate that it 
    // is added within the same array.
    return index != null ? key + '['+index+']' : key + '[]';
  }
}
```
And then the result is the follow It's just like I expected.
```php
[
    'phones' => [
        [
            'number' => '9991944318',
            'code' => '52',
            'contact' => 'Maria',
        ],
    ],
]
```

That's all. Thank you.

**Comment by therealparmesh** [comment]
So it seems like some uses cases require the index (‘a[0]’) and some do not (‘a[]’). I think we should consider adding a flag instead of forcing one way or the other.

**Comment by benoj** [comment]
+1

**Comment by therealparmesh** [comment]
@jmoguelruiz @benoj What do you think about adding a configuration flag to enable this? That way we cover all use cases.

**Comment by benoj** [comment]
I was also getting this when using an array of objects. Is the case not when the array contains objects rather than simple values?

Otherwise config would be good.

I solved my issue by simply mapping my Jason to form data manually, but deifnitly would prefer a more generic solution.

**Comment by therealparmesh** [comment]
@benoj I would point you towards the tests to see what the current expected functionality is. Do you mind sharing what you are getting versus what you are expecting?

**Comment by therealparmesh** [comment]
@jmoguelruiz @benoj Would you mind taking a look at https://github.com/therealparmesh/object-to-formdata/pull/11?

**Comment by benoj** [comment]
Will give this a test over the weekend and get back to you :)

**Comment by therealparmesh** [comment]
Closing this as I added a configuration flag to support this use case in a recent commit.
