### ISSUE TITLE
Error defining function for typescript

### ISSUE THREAD

**Issue by artar94** [therealparmesh/object-to-formdata#86]
Instead `useHovering` should be `objectToFormData`.
https://github.com/therealparmesh/object-to-formdata/blob/b0c0be74a3e510ea8be2efa56f85e4e21ba3afa7/types.d.ts#L1

**Comment by artar94** [comment]
Also `booleansAsIntegers` are missing here

**Comment by therealparmesh** [comment]
Thank you. Taking a look at this now.

**Comment by therealparmesh** [comment]
Please try version 3.0.2.
