### ISSUE TITLE
Empty arrays pass [null] instead of []

### ISSUE THREAD

**Issue by willsmanley** [therealparmesh/object-to-formdata#89]
I don't think this is the expected default behavior because it is not how axios typically handles submissions of empty arrays.

Perhaps there could be a prop to ignore empty arrays instead of passing them with a null value inside?

Currently I am working around this by using server-side middleware to convert `[null]` back to `[]`

**Comment by therealparmesh** [comment]
What version are you using? Check out the tests in the current version. They seem to cover this case.

**Comment by willsmanley** [comment]
I see that in the test, that an empty array resolves to `''`, but still on the server side the request comes through as `[null]`.

Perhaps this is a limitation of Form Data and not a package issue? I am not sure if you are able to send an empty array with form data or not.

**Comment by therealparmesh** [comment]
Thank you for reporting this! Try 3.0.6 please.

**Comment by willsmanley** [comment]
great thanks!!
