### ISSUE TITLE
Multiple Files in ASP.NET Core

### ISSUE THREAD

**Issue by jerone** [therealparmesh/object-to-formdata#93]
This is either an bug of a different implementation, but converting an array of `File` objects doesn't work in ASP.NET Core. 

For example:
```js
var model = {
	battlePlans: [new File(), new File()]
};
const formData = objectToFormData(model);
console.log(formData);

// Currently returns:
// battlePlans[]: (binary)
// battlePlans[]: (binary)
```

But apparently ASP.NET Core expects the following:
```js
var model = {
	battlePlans: [new File(), new File()]
};
const formData = objectToFormData(model);
console.log(formData);

// Expected to return:
// battlePlans: (binary)
// battlePlans: (binary)
```
_Note the missing `[]`._

The only reference from **Microsoft** saying that it should be done like this, is in [the following section](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#file-upload-scenarios):
![image](https://user-images.githubusercontent.com/55841/77228039-d4e73a00-6b84-11ea-9c64-95b0da593154.png)
The [note reference](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#match-name-attribute-value-to-parameter-name-of-post-method) to the following code example:
```js
var formData = new FormData();
for (var file in files) {
  formData.append("battlePlans", file, file.name);
}
```

**MDN** on the other side shows an [example](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append#Example) where they use the brackets, saying that this is the way to be compatible with PHP:
```js
formData.append('userpic[]', myFileInput.files[0], 'chris1.jpg');
formData.append('userpic[]', myFileInput.files[1], 'chris2.jpg');
```

**WHATWG** is _not_ specific about [this](https://xhr.spec.whatwg.org/#concept-formdata-entry-list).

This appears to be a problem only for an array of `File` objects. Other types work just fine with current implementation.

**Comment by jerone** [comment]
I created a branch that fixes this issue: https://github.com/therealparmesh/object-to-formdata/compare/master...CT-Energy:hotfix/%2393-support-multiple-files (includes test).

I'm happy to create an PR, if you believe this will not lead to breaking other applications.

**Comment by therealparmesh** [comment]
Can we hide this behind a configuration option? 😀

**Comment by jerone** [comment]
Sure, how about `noFileListBrackets`?
