### ISSUE TITLE
how to overcome the key name changes in json []

### ISSUE THREAD

**Issue by Devblues91** [therealparmesh/object-to-formdata#95]
const options = {
               indices: true,
            };
              const obj={
                  oid:1,
                  members:{
                    'roles': [],
                    'members':['cvcv']
                    }
    }

 const formData1 = objectToFormData(
                obj,options
     );

below is the key set of form data
[members[members][0], oid]
required
[members, oid]

**Comment by therealparmesh** [comment]
Can you be a little more descriptive? If you look at the tests, what seems to be wrong?
